name: Textlint 4 Markdown

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache Yarn packages
        uses: actions/cache@v2
        with:
          path: ~/.yarn-cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Cache Yarn offline mirror
        uses: actions/cache@v2
        with:
          path: ~/.yarn-offline-mirror
          key: ${{ runner.os }}-yarn-offline-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-offline-
      - name: Install dependencies with Yarn
        run: yarn install --frozen-lockfile --prefer-offline
      - name: Run Textlint
        run: yarn run textlint -- --cache --cache-location .textlintcache/ **/*.md
